### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by elupus** [devanshkv/argmark#2]
Just ran across your tool. But I got some errors when trying to run it.

```
Traceback (most recent call last):
  File "/Users/joakim/src/hass/home-assistant/venv/bin/argmark", line 8, in <module>
    sys.exit(main())
  File "/Users/joakim/src/hass/home-assistant/venv/lib/python3.9/site-packages/argmark/argmark.py", line 187, in main
    gen_help(f.readlines())
  File "/Users/joakim/src/hass/home-assistant/venv/lib/python3.9/site-packages/argmark/argmark.py", line 75, in gen_help
    lines = lines[:lastline]
```

This was trying to run on: https://github.com/danielperna84/ha-philipsjs/blob/master/haphilipsjs/__init__.py

**Comment by devanshkv** [comment]
I'll check it out.

**Comment by devanshkv** [comment]
You would have to run it on `__main__.py` because that's where the argpase arguments are defined.

Here is what I got:


python -m haphilipsjs
=====================

# Usage:


```bash
usage: python -m haphilipsjs [-h] [-d] -i HOST -a API [-u USERNAME] [-p PASSWORD] {status,monitor,ambilight,pair,markdown} ...

```
# Arguments

|short|long|default|help|
| :--- | :--- | :--- | :--- |
|`-h`|`--help`||show this help message and exit|
|`-d`|`--debug`||Debug output|
|`-i`|`--host`|`None`|`None`|
|`-a`|`--api`|`None`|`None`|
|`-u`|`--username`|`None`|Username|
|`-p`|`--password`|`None`|Password|

**Comment by devanshkv** [comment]
@elupus assuming this is resolved, I am closing the issue. Please feel free to reopen if needed.
